// ===----------------------------------------------------------------------===//
//
// This source file is part of the swift-foundations open source project
//
// Copyright (c) 2024-2025 Coen ten Thije Boonkkamp and the swift-foundations
// project authors
// Licensed under Apache License v2.0
//
// See LICENSE for license information
//
// ===----------------------------------------------------------------------===//

import Witness_Primitives

extension Witness {
    /// Captures witness context at initialization time for later use.
    ///
    /// This type is primarily used by the `@Witness.Scope` macro to ensure that
    /// objects created within a `Witness.Context.with` block retain access to
    /// that context even when methods are called from outside the block.
    ///
    /// ## Manual Usage
    ///
    /// While typically generated by `@Witness.Scope`, you can use this directly:
    ///
    /// ```swift
    /// struct FeatureModel {
    ///     private let capturedContext = Witness.CapturedContext()
    ///
    ///     func process() async throws {
    ///         try await Witness.Context.with({ $0 = capturedContext.values }) {
    ///             let api = Witness.Context.current[APIClient.self]
    ///             try await api.fetch(id: 1)
    ///         }
    ///     }
    /// }
    /// ```
    ///
    /// ## Thread Safety
    ///
    /// `CapturedContext` is `Sendable` and can be safely shared across actor boundaries.
    /// The captured values are immutable after initialization.
    public final class CapturedContext: Sendable {
        /// The captured witness values.
        public let values: Witness.Values

        /// Captures the current witness context.
        ///
        /// Call this at initialization time to capture the context that should
        /// be used for later operations.
        @inlinable
        public init() {
            self.values = Witness.Context.current
        }

        /// Executes an operation with the captured witness context.
        ///
        /// - Parameter operation: The operation to execute.
        /// - Returns: The result of the operation.
        /// - Throws: The typed error from the operation.
        @inlinable
        public func withValues<R, E: Error>(
            _ operation: () throws(E) -> R
        ) throws(E) -> R {
            try Witness.Context.with({ $0 = self.values }, operation: operation)
        }

        /// Executes an async operation with the captured witness context.
        ///
        /// - Parameter operation: The async operation to execute.
        /// - Returns: The result of the operation.
        /// - Throws: The typed error from the operation.
        @inlinable
        public func withValues<R, E: Error>(
            _ operation: () async throws(E) -> R
        ) async throws(E) -> R {
            try await Witness.Context.with({ $0 = self.values }, operation: operation)
        }
    }
}
